#define LED_PIN GPIO_NUM_2

#define BUTTON_PIN GPIO_NUM_3
#define LED_PIN GPIO_NUM_2
#define IR_SEND_PIN GPIO_NUM_5
#define IR_RECV_PIN GPIO_NUM_4

#define I2C_SCL_PIN GPIO_NUM_0
#define I2C_SDA_PIN GPIO_NUM_1
